import "./globals.css";
import Navbar from "@/components/Navbar"; 
import Footer from "@/components/Footer";

export const metadata = {
  title: "Report-BDC-CR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
        <link rel="icon" href="/WB01.ico" type="image/x-icon" />
      </head>
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
